TARGET = $(DLL_PREFIX)GpxAnalyserCore$(DLL_SUFFIX)
DEPENDENCIES = 
-include ../makefile-common-header
INCLUDES = -I./$(INCLUDE_DIR) -I./$(SRC_DIR)
LFLAGS += $(LFLAGS) -shared
-include ../makefile-common-build
